import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/ui/Header";
import AppProvider from "./components/AppContext";
import Footer from "./components/ui/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <main className="max-w-5xl mx-auto max-h-screen"> */}
        <main>
          <AppProvider>
            <Header />
            {children}
            <Footer/>
          </AppProvider>
        </main>
      </body>
    </html>
  );
}
